### ISSUE TITLE
Error requiring gem

### ISSUE THREAD

**Issue by agoodno** [codez/delayed_cron_job#26]
Hi, I'm running Ruby 2.3.1 and Rails 5.1 and I'm seeing this error. Any idea what it could be?

```irb(main):001:0> require 'delayed_cron_job'
NoMethodError: private method `attr_accessor' called for #<Class:0x007fabbbabbcb0>
Did you mean?  mattr_accessor
               cattr_accessor
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayed_cron_job-0.7.3/lib/delayed_cron_job/backend/updatable_cron.rb:7:in `included'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayed_cron_job-0.7.3/lib/delayed_cron_job.rb:27:in `include'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayed_cron_job-0.7.3/lib/delayed_cron_job.rb:27:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /Users/agoodnough/.rbenv/versions/2.3.1/bin/irb:11:in `<top (required)>'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /Users/agoodnough/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
	from /Users/agoodnough/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
	from /Users/agoodnough/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'```

**Comment by agoodno** [comment]
This is the error you get when you forget to generate and run the migration. Nothing to see here. :)

**Comment by agoodno** [comment]
Actually, it was the combination of running the migration and switching to version 0.7.2 that is working. 0.7.3 still gives me the error above. I'm assuming that it's due to the older version of Ruby and Rails.

**Comment by codez** [comment]
It's an issue with the Ruby version you use. Before Ruby 2.5, `attr_accessor` was private. Because older Ruby versions are end of life, fixing this issue has no priority.
